---
- hosts: localhost
  vars:
     helm_chart: "https://github.com/ravindra-ui/tf-anbl1.2.git"
     release_name: "grafana"

  tasks:
     - name: Create a k8s namespace
       kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present
     - name: Create a directory
       ansible.builtin.file:
        path: /tmp/helm_repository
        state: directory
     - name: Chart
       ansible.builtin.git:
        repo: "{{helm_chart}}"
        dest: /tmp/helm_repository
     - name: Deploy Grafana chart from local path
       kubernetes.core.helm:
         name: "{{release_name}}"
         chart_ref: /tmp/helm_repository/helm_charts/grafana
         release_namespace: monitoring
         values: 
          adminPassword: admin
